class Autogenerated {
  int? id;
  String? name;
  String? handler;
  String? description;
  String? category;
  String? price;
  List<String>? images;

  Autogenerated(
      {this.id,
      this.name,
      this.handler,
      this.description,
      this.category,
      this.price,
      this.images});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    handler = json['handler'];
    description = json['description'];
    category = json['category'];
    price = json['price'];
    images = json['images'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['handler'] = this.handler;
    data['description'] = this.description;
    data['category'] = this.category;
    data['price'] = this.price;
    data['images'] = this.images;
    return data;
  }
}
